### ISSUE TITLE
No module named 'cornac.utils.fast_sparse_funcs' when trying to run first.example under pycharm

### ISSUE THREAD

**Issue by yasdel** [PreferredAI/cornac#396]
### Description
Hello,
I use Ubunto version 20.04, and installed cornac using the pip3 option (under venv) and conda (under conda venv), and in both case, I am receiving this error when I want to run cornac, first example:

```
Traceback (most recent call last):
  File "/home/yas/PycharmProjects/cornac/examples/first_example.py", line 17, in <module>
    import cornac
  File "/home/yas/PycharmProjects/cornac/cornac/__init__.py", line 16, in <module>
    from . import data
  File "/home/yas/PycharmProjects/cornac/cornac/data/__init__.py", line 18, in <module>
    from .text import TextModality, ReviewModality
  File "/home/yas/PycharmProjects/cornac/cornac/data/text.py", line 27, in <module>
    from ..utils import normalize
  File "/home/yas/PycharmProjects/cornac/cornac/utils/__init__.py", line 16, in <module>
    from .common import validate_format
  File "/home/yas/PycharmProjects/cornac/cornac/utils/common.py", line 21, in <module>
    from .fast_sparse_funcs import (
ModuleNotFoundError: No module named 'cornac.utils.fast_sparse_funcs'

```
 
Let me add I use **PyCharm**.  Any idea how the issue could be handled?

**Comment by saghiles** [comment]
Hi, assuming the installation is successful, can you please let us know what is your working directory? If it is Cornac's root directory, then running the first-experiment script outside of the Cornac directory should solve the issue.

**Comment by yasdel** [comment]
sure. I tried the following working directories:

[/home/yas/PycharmProjects/cornac](url)
[/home/yas/PycharmProjects/cornac/cornac](url)
[/home/yas/PycharmProjects/cornac/examples](url)

The error is the same. I copied [first_example.py](url) here:
[/home/yas/PycharmProjects/cornac/first_example.py](url)

but the error seems to remain. Thanks for the suggestions. 

I think the installation has been correct.

**Comment by saghiles** [comment]
Welcome :). Have tried running the script from outside of Cornac (e.g., use /home/yas/PycharmProjects/ as a working directory)?

**Comment by yasdel** [comment]
Sure, I reinstalled this time from the source. The error remained the same. Then I change the working directory to `/home/yas/PycharmProjects/` and ran `/home/yas/PycharmProjects/cornac/examples/first_example.py`, and I receive the same error. It seems I am missing some information :-(

**Comment by saghiles** [comment]
I see, you may try building the Cython modules by running this command ```python setup.py build_ext --inplace```

**Comment by yasdel** [comment]
that seemed to make it work, here is the result I get:

```
FM model is only supported on Linux.
Windows executable can be found at http://www.libfm.org.

TEST:
...
    |    MAE |   RMSE |    AUC |    MAP | NDCG@10 | Precision@10 | Recall@10 | Train (s) | Test (s)
--- + ------ + ------ + ------ + ------ + ------- + ------------ + --------- + --------- + --------
MF  | 0.7430 | 0.8998 | 0.7445 | 0.0407 |  0.0479 |       0.0437 |    0.0352 |    0.0617 |   1.8576
PMF | 0.7534 | 0.9138 | 0.7744 | 0.0491 |  0.0617 |       0.0533 |    0.0479 |    3.3383 |   2.3940
BPR | 2.0143 | 2.2267 | 0.8695 | 0.0753 |  0.0975 |       0.0727 |    0.0891 |    3.3503 |   2.2055


Process finished with exit code 0
```

Could you explain what the problem was? Before under a lower version of Ubunto and using SPyder, I did not face this problem,. Thank you very much

**Comment by yasdel** [comment]
sure, and many thanks

**Comment by newlinfeng-coder** [comment]
> 伟大的！当工作目录在 Cornac 中时，将使用源代码（而不是安装的 Cornac），因此我们必须使用命令构建 Cython 模块`python setup.py build_ext --inplace`。我们应该构建 Cython 模块（无论工作目录如何）的另一种情况是从源代码安装时。既然问题已经解决了，我会继续关闭这个问题。谢谢！

Thank you for your guidance. According to the above operations, I still have the following problems:

![image](https://user-images.githubusercontent.com/28260618/126949107-ff4b697e-8b3a-4f8f-a43f-7f8603aa0d5b.png)

![image](https://user-images.githubusercontent.com/28260618/126949184-022d7657-a287-4636-89c2-336bf5a98872.png)
I am looking forward to your reply!

**Comment by CANMIDO** [comment]
> I see, you may try building the Cython modules by running this command `python setup.py build_ext --inplace`

how to solve this problem in windows platform?
